### PR TITLE
fix(api): avoid checksum query params in presigned S3 uploads

### LINKED ISSUE #1173: bug: S3 attachment uploads provide incorrect CRC values and fail
## Bug Description
I tried to add an attachment to a ticket and it failed to upload. The kaneo server returned a presigned URL with `&x-amz-checksum-crc32=AAAAAA==&x-amz-sdk-checksum-algorithm=CRC32` (i.e. only zeroes in the CRC) and the browser kaneo client then just happily tried to PUT towards it, without recalculating the CRC. My garage instance was extremely unhappy, as the real data does not have a zero CRC value and aborted the request:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>InvalidDigest</Code>
  <Message>Invalid digest: Failed to validate checksum for algorithm Crc32: calculated Some(Crc32([255, 213, 36, 122])), expected Crc32([0, 0, 0, 0])</Message>
  <Resource>/kaneo/workspace/foo/project/bar/task/bat/descriptions/aint_broke_aint_fun_blue-1775752368094-mi06elkalhz076r3444hnk8u.png</Resource>
  <Region>garage</Region>
</Error>
```

I would either proxy the upload over the backend, not include the CRC, or use the AWS SDK to generate a URL with the correct CRC.

## Steps To Reproduce
1. Go to any ticket
2. Upload any attachment
3. See error

## Expected Behavior
No error, the file should upload

## Screenshots
I don't think they will help, but here is the error popup :P

Image

## Environment
- Kaneo Version: v2.6.0
- Deployment Method: Docker
- Browser: Firefox + Chrome (both latest)
- OS: Doesn't matter, Arch Linux

## Additional Context
I set up object storage to Garage and did not find any related issue.

### PR DESCRIPTION
**Pull request by tinsever**
## Description
This PR fixes S3-compatible attachment uploads (Garage/R2) failing with `InvalidDigest` due to presigned PUT URLs containing auto-generated checksum query parameters (`x-amz-checksum-crc32` / `x-amz-sdk-checksum-algorithm`) that did not match uploaded file contents.

Changes included:
- Set the API S3 client to `requestChecksumCalculation: "WHEN_REQUIRED"` when generating presigned URLs.
- Added a regression unit test to verify generated upload URLs do not include hoisted checksum query params.

## Related Issue(s)
Fixes #1173

## Type of Change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)
- [ ] Performance improvement
- [x] Test addition or update
- [ ] Other (please describe):

## How Has This Been Tested?
- [x] Unit tests
- [ ] Integration tests
- [ ] Manual testing
- [ ] Other (please describe):

Test command run:
- `pnpm --filter @kaneo/api test:unit -- tests/api/storage/s3.test.ts`

## Screenshots (if applicable)
N/A

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

## Summary by CodeRabbit

* **Bug Fixes**
  * Updated S3 checksum handling for presigned upload URLs.

* **Tests**
  * Added test validation for presigned upload URL parameters.

### CODE REVIEW

File: apps/api/src/storage/s3.ts [hunk 1]
```diff
@@ -145,6 +145,9 @@ function getClient(config: StorageConfig) {
     endpoint: config.endpoint,
     region: config.region,
     forcePathStyle: config.forcePathStyle,
+    // Avoid auto-injecting checksum params for presigned PUT URLs. Some
+    // S3-compatible providers (e.g. Garage/R2) reject mismatched hoisted CRCs.
+    requestChecksumCalculation: "WHEN_REQUIRED",
```
Comment (I-Al-Istannen) [inline apps/api/src/storage/s3.ts:150]: Does AWS accept requests with mismatched CRC headers? The docs say AWS S3 rejects them (as I would hope!), have you tested that with AWS S3 by chance?

**Review by andrejsshell — APPROVED** [review]
